version: '3'

services:
  postgresql:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - psql-deeincom-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    restart: always

  app:
    container_name: deeincom
    image: deeincom:latest
    ports:
      - 3000:3000
    build: .
    volumes:
      - ./:/go/src/deeincom
      - deeincom_upload:/go/src/deeincom/upload

  
    
volumes:
  psql-deeincom-db-volume:
  deeincom_upload:
