create table "products"
(
    "id"                 bigserial primary key,
    "title"              varchar(255)                   not null default '',
    "category_id"        varchar(255)                   not null default '',
    "description"        text                           not null default '',
    "city"               varchar(255)                   not null default '',
    "district"           varchar(255)                   not null default '',
    "ward"               varchar(255)                   not null default '',
    "address_number"     varchar(255)                   not null default '',
    "street"             varchar(255)                   not null default '',
    "area"               integer                        not null default 0,
    "document_type"      varchar(255)                   not null default '',
    "document_proof"     varchar(255)                   not null default '',
    "bedroom"            integer                        not null default 0,
    "toilet"             integer                        not null default 0,
    "floor"              integer                        not null default 0,
    "house_direction"    varchar(255)                   not null default '',
    "balcony_direction"  varchar(255)                   not null default '',
    "front_width"        integer                        not null default 0,
    "street_width"       integer                        not null default 0,
    "pavement_width"     integer                        not null default 0,
    "business_advantage" varchar(255)                   not null default '',
    "financial_plan"     varchar(255)                   not null default '',
    "furniture"          varchar(255)                   not null default '',
    "is_activated"       boolean                        not null default false,
    "created_at"         timestamp(0) without time zone not null default '0001-01-01 00:00:00'::timestamp without time zone,
    "updated_at"         timestamp(0) without time zone not null default '0001-01-01 00:00:00'::timestamp without time zone
);
