
create table migrations (
    migration_id int generated by default as identity primary key,
    migration_version text not null default '',
    -- updated_at timestamp not null default timestamp 'epoch',
    migration_created_at timestamp with time zone not null default now()
);