
create table products (
    id int generated by default as identity primary key,
    title text not null default '',
    short_description text not null default '',
    full_description text not null default '',
    city text not null default '',
    district text not null default '',
    ward text not null default '',
    address_number text not null default '',
    street text not null default '',
    house_direction text not null default '',
    balcony_direction text not null default '',
    financial_plan text not null default '',
    furniture text not null default '',
    bedroom int not null default 0,
    toilet int not null default 0,
    floor int not null default 0,
    front_width int not null default 0,
    street_width int not null default 0,
    pavement_width int not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default '0001-01-01 00:00:00'
);

create table attachments (
    id int generated by default as identity primary key,
    title text not null default '',
    content_type text not null default '',
    mime_type text not null default '',
    link text not null default '',
    width int not null default 0,
    height int not null default 0,
    size int not null default 0,
    video_thumbnail text not null default '',
    video_length int not null default 0
);