create table posts (
    id int generated by default as identity primary key,
    title text not null default '',
    post_type text not null default '',
    slug text not null default '',
    thumbnail text not null default '',
    poster_id int not null,
    tags text[] not null default '{}',
    short text not null default '',
    content text not null default '',
    published_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

CREATE INDEX idx_posts_tags ON posts USING GIN(tags);
CREATE INDEX idx_posts_slug ON posts USING btree(slug);

create table comments (
    id int generated by default as identity primary key,
    user_id int not null,
    parent_id int,
    slug text not null,
    message text not null default '',
    is_censorship boolean not null default False,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

CREATE INDEX idx_comments_parent_id ON comments USING btree(parent_id);
CREATE INDEX idx_comments_slug ON comments USING btree(slug);