
create table logs (
    id bigint generated by default as identity primary key,
    user_id int not null,
    content text not null default '',
    created_at timestamptz not null default now()
);

CREATE INDEX idx_logs_created_at_user_id ON logs USING btree(created_at, user_id);
